### ISSUE TITLE
Feature: WIP-лимит для ячейки доски (на пересечении колонки и свимлейна)

### ISSUE THREAD

**Issue by britishpop** [Tinkoff/jira-helper#186]
**Is your feature request related to a problem? Please describe.**
Я не могу ограничить количество задач в ячейке доски, на пересечении колонки и свимлейна

**Describe the solution you'd like**
Выбрать необходимое пересечение колонки и свимлейна и установить на него лимит в настройках доски

**Describe alternatives you've considered**
Пытался ограничивать через кастомные поля, не получилось

**Additional context**
визуальное пояснение, что такое ячейка доски, на которую хочется ставить лимит
|  | To Do  | In Progress  | Done |
|:------------- |:---------------:| -------------:| -------------:|
| Tech debt      |  |  |  |
| Features    |   | ограничить здесь на перекрестке Features и In progress |  |
| Other |   |   |  |

**Comment by stepev** [comment]
Возможно, на пересечении столбцов и ячеек?

Например, если вместо in progress у нас dev и test, то можем захотеть установить общий лимит на эти две ячейки.

**Comment by britishpop** [comment]
Ну как по мне, "ячейка" это и есть пересечение столбца и свимлейна

**Comment by stepev** [comment]
|  | To Do  | Dev | Test  | Done |
| ------------- | --------------- | --------------- | ------------- | ------------- |
| Tech debt      |  |  |  |  |
| Features    |   | **ограничить общим лимитом  в двух ячейках на перекрестке Features и Dev** |  **плюс Features и Test**  |  |
| Other |   |   |  |  |

**Comment by pavelpower** [comment]
https://github.com/Tinkoff/jira-helper/pull/196

**Comment by pavelpower** [comment]
Задача выполнена https://github.com/Tinkoff/jira-helper/pull/196
